package main

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"

	"github.com/Amirhos-esm/portfolio/graph"
	"github.com/Amirhos-esm/portfolio/models"
	"github.com/Amirhos-esm/portfolio/util"
)

// UpdatePersonalInformation is the resolver for the updatePersonalInformation field.
func (r *mutationResolver) UpdatePersonalInformation(ctx context.Context, input models.UpdatePersonalInformationInput) (*models.PersonalInformation, error) {
	existing, err := r.repo.GetPersonalInformation()
	if err != nil || existing == nil {
		return nil, ErrNotFound
	}
	if err := util.PatchStruct(existing, &input); err != nil {
		return nil, err
	}
	if err := r.repo.UpdatePersonalInformation(existing); err != nil {
		return nil, err
	}

	return existing, nil
}

// CreateExperience is the resolver for the createExperience field.
func (r *mutationResolver) CreateExperience(ctx context.Context, input models.UpdateExperienceInput) (*models.Experience, error) {
	exp := models.NewExperience()
	if err := util.PatchStruct(exp, &input); err != nil {
		return nil, err
	}

	if err := r.repo.AddExperience(exp); err != nil {
		return nil, err
	}
	return exp, nil
}

// UpdateExperience is the resolver for the updateExperience field.
func (r *mutationResolver) UpdateExperience(ctx context.Context, id uint, input models.UpdateExperienceInput) (*models.Experience, error) {
	exp, err := r.repo.GetExperience(id)
	if err != nil || exp == nil {
		return nil, ErrNotFound
	}
	if err := util.PatchStruct(exp, &input); err != nil {
		return nil, err
	}

	if err := r.repo.UpdateExperience(id, exp); err != nil {
		return nil, err
	}

	return exp, nil
}

// DeleteExperience is the resolver for the deleteExperience field.
func (r *mutationResolver) DeleteExperience(ctx context.Context, id uint) (bool, error) {
	exp, err := r.repo.GetExperience(id)
	if err != nil || exp == nil {
		return false, ErrNotFound
	}

	if err := r.repo.DeleteExperience(id); err != nil {
		return false, err
	}

	return true, nil
}

// CreateEducation is the resolver for the createEducation field.
func (r *mutationResolver) CreateEducation(ctx context.Context, input models.UpdateEducationInput) (*models.Education, error) {
	educ := models.NewEducation()
	if err := util.PatchStruct(educ, &input); err != nil {
		return nil, err
	}

	if err := r.repo.AddEducation(educ); err != nil {
		return nil, err
	}
	return educ, nil
}

// UpdateEducation is the resolver for the updateEducation field.
func (r *mutationResolver) UpdateEducation(ctx context.Context, id uint, input models.UpdateEducationInput) (*models.Education, error) {
	edu, err := r.repo.GetEducation(id)
	if err != nil || edu == nil {
		return nil, ErrNotFound
	}

	if err := util.PatchStruct(edu, &input); err != nil {
		return nil, err
	}

	if err := r.repo.UpdateEducation(id, edu); err != nil {
		return nil, err
	}

	return edu, nil
}

// DeleteEducation is the resolver for the deleteEducation field.
func (r *mutationResolver) DeleteEducation(ctx context.Context, id uint) (bool, error) {
	edu, err := r.repo.GetEducation(id)
	if err != nil || edu == nil {
		return false, ErrNotFound
	}

	if err := r.repo.DeleteEducation(id); err != nil {
		return false, err
	}

	return true, nil
}

// AddTechnicalSkill is the resolver for the addTechnicalSkill field.
func (r *mutationResolver) AddTechnicalSkill(ctx context.Context, skill string) (*models.Skills, error) {
	skills, err := r.repo.GetSkills()
	if err != nil || skills == nil {
		return nil, ErrNotFound
	}

	if !skills.AddTecknicalSkill(skill) {
		return skills, nil
	}

	if err := r.repo.UpdateSkills(skills); err != nil {
		return nil, err
	}

	return skills, nil
}

// RemoveTechnicalSkill is the resolver for the removeTechnicalSkill field.
func (r *mutationResolver) RemoveTechnicalSkill(ctx context.Context, skill string) (*models.Skills, error) {
	skills, err := r.repo.GetSkills()
	if err != nil || skills == nil {
		return nil, ErrNotFound
	}

	if !skills.DeleteTecknicalSkill(skill) {
		return skills, nil
	}

	if err := r.repo.UpdateSkills(skills); err != nil {
		return nil, err
	}

	return skills, nil
}

// AddSoftSkill is the resolver for the addSoftSkill field.
func (r *mutationResolver) AddSoftSkill(ctx context.Context, skill string) (*models.Skills, error) {
	skills, err := r.repo.GetSkills()
	if err != nil || skills == nil {
		return nil, ErrNotFound
	}

	if !skills.AddSoftSkill(skill) {
		return skills, nil
	}

	if err := r.repo.UpdateSkills(skills); err != nil {
		return nil, err
	}

	return skills, nil
}

// RemoveSoftSkill is the resolver for the removeSoftSkill field.
func (r *mutationResolver) RemoveSoftSkill(ctx context.Context, skill string) (*models.Skills, error) {
	skills, err := r.repo.GetSkills()
	if err != nil || skills == nil {
		return nil, ErrNotFound
	}

	if !skills.DeleteSoftSkill(skill) {
		return skills, nil
	}

	if err := r.repo.UpdateSkills(skills); err != nil {
		return nil, err
	}

	return skills, nil
}

// CreateProject is the resolver for the createProject field.
func (r *mutationResolver) CreateProject(ctx context.Context, input models.ProjectBasicUpdateInput) (*models.Project, error) {
	project := models.NewProject()
	if err := util.PatchStruct(project, &input); err != nil {
		return nil, err
	}

	if err := r.repo.AddProject(project); err != nil {
		return nil, err
	}
	return project, nil
}

// UpdateProjectBasic is the resolver for the updateProjectBasic field.
func (r *mutationResolver) UpdateProjectBasic(ctx context.Context, projectID uint, input models.ProjectBasicUpdateInput) (*models.Project, error) {
	project, err := r.repo.GetProject(projectID)
	if err != nil || project == nil {
		return nil, ErrNotFound
	}

	if err := util.PatchStruct(project, &input); err != nil {
		return nil, err
	}

	if err := r.repo.UpdateProject(projectID, project); err != nil {
		return nil, err
	}

	return project, nil
}

// UpdateProjectTags is the resolver for the updateProjectTags field.
func (r *mutationResolver) UpdateProjectTags(ctx context.Context, projectID uint, ops models.StringListOpsInput) (*models.Project, error) {
	project, err := r.repo.GetProject(projectID)
	if err != nil || project == nil {
		return nil, ErrNotFound
	}

	for _, tag := range ops.Add {
		project.AddTag(tag)
	}
	for _, tag := range ops.Remove {
		project.RemoveTag(tag)
	}

	if err := r.repo.UpdateProject(projectID, project); err != nil {
		return nil, err
	}

	return project, nil
}

// UpdateProjectTechStack is the resolver for the updateProjectTechStack field.
func (r *mutationResolver) UpdateProjectTechStack(ctx context.Context, projectID uint, updates []*models.TechStackUpdateInput) (*models.Project, error) {
	project, err := r.repo.GetProject(projectID)
	if err != nil || project == nil {
		return nil, ErrNotFound
	}

	for _, u := range updates {
		if u.Ops.Add != nil {
			for _, teck := range u.Ops.Add {
				project.AddTech(u.Key, teck)
			}
		}
		if u.Ops.Remove != nil {
			for _, teck := range u.Ops.Remove {
				project.RemoveTech(u.Key, teck)
			}
		}
	}

	if err := r.repo.UpdateProject(projectID, project); err != nil {
		return nil, err
	}

	return project, nil
}

// AddProjectFeature is the resolver for the addProjectFeature field.
func (r *mutationResolver) AddProjectFeature(ctx context.Context, projectID uint, input models.CreateProjectFeatureInput) (*models.ProjectFeature, error) {
	project, err := r.repo.GetProject(projectID)
	if err != nil || project == nil {
		return nil, ErrNotFound
	}

	feature := &models.ProjectFeature{
		Title:       input.Title,
		Description: input.Description,
	}

	project.AddFeature(feature)

	if err := r.repo.UpdateProject(projectID, project); err != nil {
		return nil, err
	}
	return feature, nil
}

// UpdateProjectFeature is the resolver for the updateProjectFeature field.
func (r *mutationResolver) UpdateProjectFeature(ctx context.Context, projectID uint, featureID uint, input models.UpdateProjectFeatureInput) (*models.ProjectFeature, error) {
	project, err := r.repo.GetProject(projectID)
	if err != nil || project == nil {
		return nil, ErrNotFound
	}

	for _, f := range project.Features {
		if f.ID == featureID {
			if err := util.PatchStruct(f, &input); err != nil {
				return nil, err
			}
			if err := r.repo.UpdateProject(projectID, project); err != nil {
				return nil, err
			}
			return f, nil
		}
	}

	return nil, ErrNotFound
}

// DeleteProjectFeature is the resolver for the deleteProjectFeature field.
func (r *mutationResolver) DeleteProjectFeature(ctx context.Context, projectID uint, featureID uint) (bool, error) {
	project, err := r.repo.GetProject(projectID)
	if err != nil || project == nil || !project.RemoveFeature(featureID) {
		return false, ErrNotFound
	}
	if err := r.repo.UpdateProject(projectID, project); err != nil {
		return false, err
	}
	return true, nil
}

// DeleteProjectGallery is the resolver for the deleteProjectGallery field.
func (r *mutationResolver) DeleteProjectGallery(ctx context.Context, projectID uint, imageID string) (bool, error) {
	project, err := r.repo.GetProject(projectID)
	if err != nil || project == nil || !project.RemoveGalleryImage(imageID) {
		return false, ErrNotFound
	}
	if err := r.repo.UpdateProject(projectID, project); err != nil {
		return false, err
	}
	return true, nil
}

// PersonalInformation is the resolver for the personalInformation field.
func (r *queryResolver) PersonalInformation(ctx context.Context) (*models.PersonalInformation, error) {
	personal, err := r.repo.GetPersonalInformation()
	if err != nil || personal == nil {
		return nil, ErrNotFound
	}
	return personal, nil
}

// Skills is the resolver for the skills field.
func (r *queryResolver) Skills(ctx context.Context) (*models.Skills, error) {
	return r.repo.GetSkills()
}

// Educations is the resolver for the educations field.
func (r *queryResolver) Educations(ctx context.Context) ([]*models.Education, error) {
	educations, err := r.repo.GetAllEducation()
	if err != nil || educations == nil {
		return nil, ErrNotFound
	}
	return educations, nil
}

// Education is the resolver for the education field.
func (r *queryResolver) Education(ctx context.Context, id uint) (*models.Education, error) {
	education, err := r.repo.GetEducation(id)
	if err != nil || education == nil {
		return nil, ErrNotFound
	}
	return education, nil
}

// Experiences is the resolver for the experiences field.
func (r *queryResolver) Experiences(ctx context.Context) ([]*models.Experience, error) {
	experiences, err := r.repo.GetAllExperiences()
	if err != nil || experiences == nil {
		return nil, ErrNotFound
	}
	return experiences, nil
}

// Experience is the resolver for the experience field.
func (r *queryResolver) Experience(ctx context.Context, id uint) (*models.Experience, error) {
	experience, err := r.repo.GetExperience(id)
	if err != nil || experience == nil {
		return nil, ErrNotFound
	}
	return experience, nil
}

// Projects is the resolver for the projects field.
func (r *queryResolver) Projects(ctx context.Context) ([]*models.Project, error) {
	projects, err := r.repo.GetAllProjects()
	if err != nil || projects == nil {
		return nil, ErrNotFound
	}
	return projects, nil
}

// Project is the resolver for the project field.
func (r *queryResolver) Project(ctx context.Context, id uint) (*models.Project, error) {
	project, err := r.repo.GetProject(id)
	if err != nil || project == nil {
		return nil, ErrNotFound
	}
	return project, nil
}

// Mutation returns graph.MutationResolver implementation.
func (r *Resolver) Mutation() graph.MutationResolver { return &mutationResolver{r} }

// Query returns graph.QueryResolver implementation.
func (r *Resolver) Query() graph.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
/*
	func GetPreloads(ctx context.Context) []string {
	return GetNestedPreloads(
		graphql.GetOperationContext(ctx),
		graphql.CollectFieldsCtx(ctx, nil),
		"",
	)
}
func GetNestedPreloads(ctx *graphql.OperationContext, fields []graphql.CollectedField, prefix string) (preloads []string) {
	for _, column := range fields {
		prefixColumn := GetPreloadString(prefix, column.Name)
		preloads = append(preloads, prefixColumn)
		preloads = append(preloads, GetNestedPreloads(ctx, graphql.CollectFields(ctx, column.Selections, nil), prefixColumn)...)
	}
	return
}
func GetPreloadString(prefix, name string) string {
	if len(prefix) > 0 {
		return prefix + "." + name
	}
	return name
}
*/
