// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

import (
	"time"
)

type CreateMessageInput struct {
	Fullname string `json:"fullname"`
	Email    string `json:"email"`
	Message  string `json:"message"`
}

type CreateProjectFeatureInput struct {
	Title       string `json:"title"`
	Description string `json:"description"`
	Icon        string `json:"icon"`
}

type Education struct {
	ID          uint       `json:"id"`
	Degree      string     `json:"degree"`
	School      string     `json:"school"`
	Location    string     `json:"location"`
	StartDate   time.Time  `json:"startDate"`
	EndDate     *time.Time `json:"endDate,omitempty"`
	Description string     `json:"description"`
}

type Experience struct {
	ID          uint       `json:"id"`
	JobTitle    string     `json:"jobTitle"`
	Company     string     `json:"company"`
	Location    string     `json:"location"`
	StartDate   time.Time  `json:"startDate"`
	EndDate     *time.Time `json:"endDate,omitempty"`
	Description string     `json:"description"`
}

type Message struct {
	ID       uint      `json:"id"`
	Fullname string    `json:"fullname"`
	Email    string    `json:"email"`
	Message  string    `json:"message"`
	Createat time.Time `json:"createat"`
}

type MessagePageInput struct {
	Offset *int32 `json:"offset,omitempty"`
	Limit  *int32 `json:"limit,omitempty"`
}

type Mutation struct {
}

type PersonalInformation struct {
	FullName          string      `json:"fullName"`
	ProfessionalTitle string      `json:"professionalTitle"`
	ProfileImage      string      `json:"profileImage"`
	Bio               string      `json:"bio"`
	Email             string      `json:"email"`
	Phone             string      `json:"phone"`
	Location          string      `json:"location"`
	SocialLink        *SocialLink `json:"socialLink"`
}

type Project struct {
	ID               uint    `json:"id"`
	Title            string  `json:"title"`
	ShortDescription string  `json:"shortDescription"`
	Description      string  `json:"description"`
	LiveURL          *string `json:"liveUrl,omitempty"`
	RepositoryURL    *string `json:"repositoryUrl,omitempty"`
	MyRole           string  `json:"myRole"`
	Duration         string  `json:"duration"`
	Client           string  `json:"client"`
	// tags
	Tags []string `json:"tags"`
	// id of the image stored in the galleryImages field, the url can be constructed by /static/{project_id}/{id}
	GalleryImages []string `json:"galleryImages"`
	// a hashmap like object map[string][]string
	TechStack map[string][]string `json:"techStack"`
	Features  []*ProjectFeature   `json:"features"`
}

type ProjectBasicUpdateInput struct {
	Title            *string `json:"title,omitempty"`
	ShortDescription *string `json:"shortDescription,omitempty"`
	Description      *string `json:"description,omitempty"`
	LiveURL          *string `json:"liveUrl,omitempty"`
	RepositoryURL    *string `json:"repositoryUrl,omitempty"`
	MyRole           *string `json:"myRole,omitempty"`
	Duration         *string `json:"duration,omitempty"`
	Client           *string `json:"client,omitempty"`
}

type ProjectFeature struct {
	ID          uint   `json:"id"`
	Title       string `json:"title"`
	Description string `json:"description"`
	Icon        string `json:"icon"`
}

type Query struct {
}

type Skills struct {
	Technical []string `json:"technical"`
	Soft      []string `json:"soft"`
}

type SkillsPatchInput struct {
	Technical []string `json:"technical,omitempty"`
	Soft      []string `json:"soft,omitempty"`
}

type SocialLink struct {
	Linkedin string `json:"linkedin"`
	Github   string `json:"github"`
	Telegram string `json:"telegram"`
}

type StringListOpsInput struct {
	Add     []string `json:"add,omitempty"`
	Remove  []string `json:"remove,omitempty"`
	Replace []string `json:"replace,omitempty"`
}

type TechStackUpdateInput struct {
	Key string              `json:"key"`
	Ops *StringListOpsInput `json:"ops"`
}

type UpdateEducationInput struct {
	Degree      *string    `json:"degree,omitempty"`
	School      *string    `json:"school,omitempty"`
	StartDate   *time.Time `json:"startDate,omitempty"`
	Location    *string    `json:"location,omitempty"`
	EndDate     *time.Time `json:"endDate,omitempty"`
	Description *string    `json:"description,omitempty"`
}

type UpdateExperienceInput struct {
	JobTitle    *string    `json:"jobTitle,omitempty"`
	Company     *string    `json:"company,omitempty"`
	Location    *string    `json:"location,omitempty"`
	StartDate   *time.Time `json:"startDate,omitempty"`
	EndDate     *time.Time `json:"endDate,omitempty"`
	Description *string    `json:"description,omitempty"`
}

type UpdatePersonalInformationInput struct {
	FullName          *string                `json:"fullName,omitempty"`
	ProfessionalTitle *string                `json:"professionalTitle,omitempty"`
	Bio               *string                `json:"bio,omitempty"`
	Email             *string                `json:"email,omitempty"`
	Phone             *string                `json:"phone,omitempty"`
	Location          *string                `json:"location,omitempty"`
	ProfileImage      *string                `json:"profileImage,omitempty"`
	SocialLink        *UpdateSocialLinkInput `json:"socialLink,omitempty"`
}

type UpdateProjectFeatureInput struct {
	Title       *string `json:"title,omitempty"`
	Description *string `json:"description,omitempty"`
	Icon        *string `json:"icon,omitempty"`
}

type UpdateSocialLinkInput struct {
	Linkedin *string `json:"linkedin,omitempty"`
	Github   *string `json:"github,omitempty"`
	Telegram *string `json:"telegram,omitempty"`
}
